# Numpy exercises

In [1]:
import numpy as np
import pandas as pd

## 1 eigenvalues

In [2]:
A = np.array([[4, 2, 3],
              [1, 3, 2],
              [5, 6, 2]])
values, vectors = np.linalg.eig(A)
values

array([ 8.89490179,  2.03688771, -1.93178949])

## 2 eigenvectors

In [3]:
vectors

array([[-0.58909418, -0.76580857, -0.35249971],
       [-0.34745221,  0.63863715, -0.28942125],
       [-0.72955124,  0.07536464,  0.88993219]])

## 3 matrix mult

In [4]:
B = np.array([[3, 1, 6],
              [2, 2, 2],
              [4, 5, 1]])

In [5]:
A @ B

array([[28, 23, 31],
       [17, 17, 14],
       [35, 27, 44]])

## 4 Diagonal

In [6]:
B_diagonal = np.diag(B)
B_diagonal

array([3, 2, 1])

## 5 Inverse

In [7]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 1.33333333, -4.83333333,  1.66666667],
       [-1.        ,  3.5       , -1.        ],
       [-0.33333333,  1.83333333, -0.66666667]])

## 6 Diagonalization

In [8]:
values, vectors = np.linalg.eig(A)
D = np.diag(values)
P = vectors
P_inv = np.linalg.inv(P)
try:
    P @ D @ P_inv
except Exception:
    print('matrix A cannot be diagonalized')
else:
    print('matrix A can be diagonalized')

matrix A can be diagonalized


## 7 moving avg

In [9]:
data = np.random.randn(100)
mask = np.random.choice([1, 0], size=data.shape, p=[0.33, 0.67]).astype(bool)  # 33% are missing

data_with_nans = data.copy()
data_with_nans[mask] = np.nan

df = pd.DataFrame(data_with_nans, columns=["data"])
df["filled"] = df["data"].fillna(df["data"].rolling(window=5, min_periods=1).mean())
df.head()

data    filled
0  0.021103  0.021103
1       NaN  0.021103
2       NaN  0.021103
3       NaN  0.021103
4  1.406702  1.406702

## 8 Find Percentile

In [10]:
data = np.random.randint(0, 101, 100)
percentile = np.percentile(data, 50)
percentile, data.mean()

(49.0, 49.94)

## 9 Corr coef

In [11]:
x = np.random.rand(100)
y = np.random.rand(100)
correlation_coefficient = np.corrcoef(x, y)[0, 1]
correlation_coefficient

-0.1624592912743462

## 10 Standard deviation

In [12]:
np.std(x)

0.30541917725522477

## 11 Variance 

In [13]:
np.var(x)

0.0932808738352584

## 12 Median

In [14]:
np.median(x)

0.5045792212145404

## 13 IQR 

In [15]:
np.percentile(x, 75) - np.percentile(x, 25)

0.5820583553976821

## 14 counts of unique

In [16]:
np.unique(x, return_counts=True)

(array([0.00553076, 0.00719377, 0.00954303, 0.0135926 , 0.0166969 ,
        0.02481163, 0.04758412, 0.06470791, 0.092426  , 0.10095724,
        0.10175469, 0.1062509 , 0.10720524, 0.11787714, 0.13540933,
        0.13988537, 0.14038027, 0.14092414, 0.1494615 , 0.1503082 ,
        0.1508052 , 0.16128882, 0.1634236 , 0.1650056 , 0.18628243,
        0.19785244, 0.21892123, 0.2289648 , 0.2302866 , 0.23499985,
        0.23518543, 0.24529938, 0.25077651, 0.30348468, 0.3450569 ,
        0.34955726, 0.35331833, 0.356554  , 0.37428413, 0.37523628,
        0.38478833, 0.38766824, 0.39420992, 0.40098468, 0.40618357,
        0.45516763, 0.47182312, 0.47463617, 0.48128928, 0.50379192,
        0.50536652, 0.50757947, 0.51677311, 0.53595492, 0.54728498,
        0.55452209, 0.55665123, 0.56898542, 0.57768651, 0.5875503 ,
        0.58889982, 0.59149599, 0.59806958, 0.60888184, 0.62770573,
        0.6284552 , 0.64539432, 0.65269608, 0.66299577, 0.6838879 ,
        0.68770879, 0.69924526, 0.70159965, 0.75

## 15 logic

In [17]:
np.where(x > 0.4, 'more', 'less')

array(['less', 'less', 'more', 'more', 'more', 'more', 'more', 'more',
       'less', 'more', 'more', 'less', 'more', 'less', 'more', 'less',
       'less', 'less', 'more', 'less', 'less', 'less', 'less', 'more',
       'more', 'more', 'less', 'less', 'more', 'less', 'less', 'less',
       'more', 'more', 'less', 'less', 'less', 'more', 'less', 'more',
       'less', 'more', 'less', 'more', 'more', 'more', 'more', 'less',
       'more', 'less', 'more', 'more', 'more', 'less', 'more', 'more',
       'less', 'more', 'more', 'less', 'more', 'less', 'less', 'more',
       'less', 'more', 'more', 'less', 'more', 'more', 'more', 'more',
       'more', 'more', 'less', 'more', 'less', 'less', 'more', 'more',
       'less', 'more', 'less', 'more', 'more', 'more', 'more', 'more',
       'more', 'less', 'more', 'less', 'less', 'less', 'less', 'less',
       'more', 'more', 'more', 'more'], dtype='<U4')